#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;

namespace RatHabitat.Editor
{
    /// <summary>
    /// Slices the single imported Take 001 into standalone AnimationClip assets.
    /// The importer is configured through ModelImporter so the full source take
    /// is available without hand-editing Unity's serialized split table.
    /// </summary>
    public static class HandPaintedRatAnimationSetup
    {
        private const string ModelPath = "Assets/Art/HandPaintedRat/HandPaintedRat.fbx";
        private const string ControllerPath = "Assets/Prefabs/HandPaintedRat/HandPaintedRat.controller";
        private const string ClipFolderPath = "Assets/Art/HandPaintedRat/AnimationClips";
        private const string RuntimeAuditPath = "Assets/Resources/HandPaintedRat/HandPaintedRatAnimationAudit.asset";
        private const string CombinedTakeName = "Take 001";
        private const string AutomaticRepairSessionKey = "RatHabitat.HandPaintedRatAnimationRangeRepairAttempted";
        private const int SourceTimelineFirstFrame = 1;
        private const int SourceTimelineLastFrame = 256;
        private const float SourceFrameRateFallback = 24f;
        private static bool bakeQueued;

        private struct ClipRange
        {
            public string name;
            public int firstFrame;
            public int lastFrame;
            public bool loop;
            // When true, lastFrame is the final included source frame. This
            // prevents the slicer from sampling the following transition
            // frame as the clip's end boundary.
            public bool inclusiveEnd;

            public ClipRange(string name, int firstFrame, int lastFrame, bool loop, bool inclusiveEnd = false)
            {
                this.name = name;
                this.firstFrame = firstFrame;
                this.lastFrame = lastFrame;
                this.loop = loop;
                this.inclusiveEnd = inclusiveEnd;
            }
        }

        // Frame 1 is the first source frame. Idle is intentionally not baked
        // or added to the controller. The walk window starts at source
        // frame 33 to remove the initial held pose. Source frame 65
        // begins the authored transition into the next action: the tail
        // straightens and the body briefly returns to a stiff reset pose.
        // Keep that transition out of the looping walk clip.
        private static readonly ClipRange[] ClipRanges =
        {
            new ClipRange("HandPaintedRat_Walk", 33, 64, true, true),
            new ClipRange("HandPaintedRat_IdleReaction", 67, 96, false),
            new ClipRange("HandPaintedRat_Run", 99, 128, true),
            new ClipRange("HandPaintedRat_Sniffing", 129, 161, false),
            new ClipRange("HandPaintedRat_Dying", 162, 192, false),
            new ClipRange("HandPaintedRat_Jump", 193, 224, false),
            new ClipRange("HandPaintedRat_Attack", 225, 256, false),
        };

        [InitializeOnLoadMethod]
        private static void EnsureGeneratedClipsAreUsable()
        {
            EditorApplication.delayCall -= RepairGeneratedClipsIfNeeded;
            EditorApplication.delayCall += RepairGeneratedClipsIfNeeded;
        }

        private static void RepairGeneratedClipsIfNeeded()
        {
            AnimationClip walk = AssetDatabase.LoadAssetAtPath<AnimationClip>(ClipFolderPath + "/HandPaintedRat_Walk.anim");
            AnimationClip run = AssetDatabase.LoadAssetAtPath<AnimationClip>(ClipFolderPath + "/HandPaintedRat_Run.anim");
            AnimationClip reaction = AssetDatabase.LoadAssetAtPath<AnimationClip>(ClipFolderPath + "/HandPaintedRat_IdleReaction.anim");
            bool rangesMatch = HasExpectedDuration(walk, ClipRanges[0]) &&
                HasExpectedDuration(reaction, ClipRanges[1]) &&
                HasExpectedDuration(run, ClipRanges[2]) &&
                HasExpectedSourceRanges();
            if (HasUsableLoopingMotion(walk) && HasUsableLoopingMotion(run) && rangesMatch)
            {
                // Keep the runtime showcase's curve status current even when
                // the clips were generated by an earlier explicit rebuild.
                WriteRuntimeAuditForExistingClips();
                return;
            }

            // If Unity has already exposed the confirmed full source take,
            // repair once automatically after the domain reload. SessionState
            // prevents an import/domain-reload loop; the explicit menu remains
            // available for a later manual retry.
            AnimationClip source = LoadCombinedTake();
            string currentRangeSignature = DescribeRanges();
            if (HasFullSourceTimeline(source) && !string.Equals(SessionState.GetString(AutomaticRepairSessionKey, string.Empty), currentRangeSignature, StringComparison.Ordinal))
            {
                SessionState.SetString(AutomaticRepairSessionKey, currentRangeSignature);
                Debug.Log("[Rat Habitat] Full Hand Painted Rat source take is imported; queuing one safe range repair.");
                ScheduleBakeAndRebuild();
                return;
            }

            // Do not reimport automatically while Unity is opening. The old
            // generated clips are safe to inspect, but an importer reimport is
            // an explicit operation because this FBX previously crashed while
            // processing hand-authored split metadata. The rebuild menu below
            // configures one complete source take through ModelImporter, then
            // the postprocessor bakes after that reimport completes.
            Debug.LogWarning("[Rat Habitat] Hand Painted Rat generated clips are missing, unusable, or stale for the confirmed frame ranges. Run Rat Habitat > Visuals > Rebuild Hand Painted Rat Animation Controller after the FBX finishes importing.");
        }

        private static bool HasFullSourceTimeline(AnimationClip clip)
        {
            if (clip == null) return false;
            float frameRate = clip.frameRate > 0f ? clip.frameRate : SourceFrameRateFallback;
            float minimumLength = (SourceTimelineLastFrame - 1) / frameRate;
            return clip.length >= minimumLength - (1f / frameRate) * 0.5f;
        }

        private static bool HasExpectedDuration(AnimationClip clip, ClipRange range)
        {
            if (clip == null || clip.frameRate <= 0f) return false;
            float expectedLength = GetExpectedDuration(range, clip.frameRate);
            float oneFrame = 1f / clip.frameRate;
            return Mathf.Abs(clip.length - expectedLength) <= oneFrame * 0.2f;
        }

        private static float GetExpectedDuration(ClipRange range, float frameRate)
        {
            if (frameRate <= 0f) frameRate = SourceFrameRateFallback;
            if (range.inclusiveEnd)
            {
                return Mathf.Max(1f / frameRate, (range.lastFrame - range.firstFrame) / frameRate);
            }

            return (range.lastFrame - range.firstFrame + 1) / frameRate;
        }

        private static float GetEndTime(ClipRange range, float frameRate)
        {
            if (frameRate <= 0f) frameRate = SourceFrameRateFallback;
            int finalIncludedSourceFrame = range.inclusiveEnd ? range.lastFrame : range.lastFrame + 1;
            float startTime = (range.firstFrame - 1) / frameRate;
            float endTime = (finalIncludedSourceFrame - 1) / frameRate;
            return Mathf.Max(startTime + 1f / frameRate, endTime);
        }

        private static void WriteRuntimeAuditForExistingClips()
        {
            var clips = new AnimationClip[ClipRanges.Length];
            for (int i = 0; i < ClipRanges.Length; i++)
            {
                clips[i] = AssetDatabase.LoadAssetAtPath<AnimationClip>(ClipFolderPath + "/" + ClipRanges[i].name + ".anim");
                if (clips[i] == null) return;
            }

            WriteRuntimeAudit(clips);
            AssetDatabase.SaveAssets();
        }

        private static bool HasUsableLoopingMotion(AnimationClip clip)
        {
            if (clip == null) return false;
            AnimationClipSettings settings = AnimationUtility.GetAnimationClipSettings(clip);
            if (!settings.loopTime) return false;

            EditorCurveBinding[] bindings = AnimationUtility.GetCurveBindings(clip);
            for (int i = 0; i < bindings.Length; i++)
            {
                if (!IsBodyMotionBinding(bindings[i])) continue;
                AnimationCurve curve = AnimationUtility.GetEditorCurve(clip, bindings[i]);
                if (curve == null || curve.length < 2) continue;
                float first = curve[0].value;
                for (int k = 1; k < curve.length; k++)
                {
                    if (Mathf.Abs(curve[k].value - first) > 0.0001f) return true;
                }
            }
            return false;
        }

        [MenuItem("Rat Empire/Visuals/Rebuild Hand Painted Rat Animation Controller")]
        public static void RebuildFromImportedModel()
        {
            ConfigureFullTimelineImporter();
        }

        private static bool ConfigureFullTimelineImporter()
        {
            ModelImporter importer = AssetImporter.GetAtPath(ModelPath) as ModelImporter;
            if (importer == null)
            {
                Debug.LogError("[Rat Habitat] Could not access the Hand Painted Rat ModelImporter at " + ModelPath + ".");
                return false;
            }

            importer.importAnimation = true;
            importer.animationType = ModelImporterAnimationType.Generic;
            importer.optimizeGameObjects = false;

            // Keep Unity's handwritten clipAnimations table empty. Unity still
            // imports the embedded source takes with importAnimation enabled;
            // the confirmed boundaries are baked into standalone .anim assets
            // only after the full source take is available. The old serialized
            // split table was the source of a Unity 2022.3.40f1 crash.
            importer.clipAnimations = new ModelImporterClipAnimation[0];

            Debug.Log("[Rat Habitat] Reimporting Hand Painted Rat with animation import enabled, Generic rig, and empty handwritten clip table. Expected source timeline=" +
                SourceTimelineFirstFrame + "-" + SourceTimelineLastFrame + ".");
            importer.SaveAndReimport();
            return true;
        }

        internal static void ScheduleBakeAndRebuild()
        {
            if (bakeQueued) return;
            bakeQueued = true;
            EditorApplication.delayCall -= BakeAndRebuildController;
            EditorApplication.delayCall += BakeAndRebuildController;
        }

        private static void BakeAndRebuildController()
        {
            bakeQueued = false;
            AnimationClip sourceClip = LoadCombinedTake();
            if (sourceClip == null)
            {
                Debug.LogError("[Rat Habitat] Could not find the imported '" + CombinedTakeName + "' animation in " + ModelPath + ". The FBX must finish importing before the split can be baked.");
                return;
            }

            float sourceFrameRate = sourceClip.frameRate > 0f ? sourceClip.frameRate : SourceFrameRateFallback;
            float minimumSourceLength = (SourceTimelineLastFrame - 1) / sourceFrameRate;
            if (sourceClip.length < minimumSourceLength - (1f / sourceFrameRate) * 0.5f)
            {
                Debug.LogError("[Rat Habitat] Refusing to bake animation clips from a short or stale source clip. Selected source='" + sourceClip.name + "' length=" + sourceClip.length.ToString("0.###") + "s, expected the confirmed " + SourceTimelineFirstFrame + "-" + SourceTimelineLastFrame + " timeline to reach at least " + minimumSourceLength.ToString("0.###") + "s. Reimport the FBX, then run the rebuild menu again.");
                return;
            }

            EditorCurveBinding[] sourceBindings = AnimationUtility.GetCurveBindings(sourceClip);
            Debug.Log("[Rat Habitat] Hand Painted Rat source audit: clip=" + sourceClip.name +
                " length=" + sourceClip.length.ToString("0.###") + "s frameRate=" + sourceFrameRate.ToString("0.###") +
                " floatBindings=" + sourceBindings.Length +
                " objectBindings=" + AnimationUtility.GetObjectReferenceCurveBindings(sourceClip).Length);

            EnsureFolder(ClipFolderPath);
            string staleIdlePath = ClipFolderPath + "/HandPaintedRat_Idle.anim";
            if (AssetDatabase.LoadAssetAtPath<AnimationClip>(staleIdlePath) != null)
            {
                AssetDatabase.DeleteAsset(staleIdlePath);
                Debug.Log("[Rat Habitat] Removed stale generated Idle clip; stationary rats now hold a static pose.");
            }
            AnimationClip[] slicedClips = new AnimationClip[ClipRanges.Length];
            bool allClipsValid = true;
            for (int i = 0; i < ClipRanges.Length; i++)
            {
                slicedClips[i] = CreateOrReplaceSlicedClip(sourceClip, ClipRanges[i]);
                AnimationClipSettings settings = AnimationUtility.GetAnimationClipSettings(slicedClips[i]);
                bool hasCurves = slicedClips[i] != null && CountAnimatedBindings(slicedClips[i]) > 0;
                bool hasBodyCurves = slicedClips[i] != null && CountAnimatedBodyBindings(slicedClips[i]) > 0;
                bool hasExpectedRange = HasExpectedDuration(slicedClips[i], ClipRanges[i]);
                bool validClip = slicedClips[i] != null && hasCurves && hasBodyCurves && hasExpectedRange &&
                    settings.loopTime == ClipRanges[i].loop;
                if (!validClip) allClipsValid = false;
                Debug.Log("[Rat Habitat] Hand Painted Rat clip audit: clip=" + slicedClips[i].name +
                    " range=" + ClipRanges[i].firstFrame + "-" + ClipRanges[i].lastFrame +
                    " length=" + slicedClips[i].length.ToString("0.###") + "s" +
                    " floatBindings=" + AnimationUtility.GetCurveBindings(slicedClips[i]).Length +
                    " loopTime=" + settings.loopTime +
                    " animatedBindings=" + CountAnimatedBindings(slicedClips[i]) +
                    " animatedBodyBindings=" + CountAnimatedBodyBindings(slicedClips[i]) +
                    " valid=" + validClip);
            }

            if (!allClipsValid)
            {
                Debug.LogError("[Rat Habitat] Refusing to rebuild the Hand Painted Rat controller because one or more generated clips is empty, stale, has the wrong range, or lacks animated body curves.");
                return;
            }

            WriteRuntimeAudit(slicedClips);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            RebuildController(slicedClips);
        }

        private static void WriteRuntimeAudit(AnimationClip[] clips)
        {
            EnsureFolder("Assets/Resources");
            EnsureFolder("Assets/Resources/HandPaintedRat");

            RatAnimationClipAudit audit = AssetDatabase.LoadAssetAtPath<RatAnimationClipAudit>(RuntimeAuditPath);
            if (audit == null)
            {
                audit = ScriptableObject.CreateInstance<RatAnimationClipAudit>();
                AssetDatabase.CreateAsset(audit, RuntimeAuditPath);
            }

            if (audit.entries == null) audit.entries = new List<RatAnimationClipAudit.Entry>();
            audit.entries.Clear();
            for (int i = 0; i < clips.Length; i++)
            {
                AnimationClip clip = clips[i];
                audit.entries.Add(new RatAnimationClipAudit.Entry
                {
                    clipName = clip == null ? string.Empty : clip.name,
                    available = clip != null,
                    floatBindings = clip == null ? 0 : AnimationUtility.GetCurveBindings(clip).Length,
                    animatedBindings = clip == null ? 0 : CountAnimatedBindings(clip),
                    animatedBodyBindings = clip == null ? 0 : CountAnimatedBodyBindings(clip),
                    lengthSeconds = clip == null ? 0f : clip.length,
                    sourceFirstFrame = ClipRanges[i].firstFrame,
                    sourceLastFrame = ClipRanges[i].lastFrame,
                });
            }

            EditorUtility.SetDirty(audit);
            Debug.Log("[Rat Habitat] Runtime animation audit asset updated at " + RuntimeAuditPath + ".");
        }

        private static bool HasExpectedSourceRanges()
        {
            RatAnimationClipAudit audit = AssetDatabase.LoadAssetAtPath<RatAnimationClipAudit>(RuntimeAuditPath);
            if (audit == null || audit.entries == null) return false;

            for (int i = 0; i < ClipRanges.Length; i++)
            {
                RatAnimationClipAudit.Entry entry = audit.Find(ClipRanges[i].name);
                if (entry == null || entry.sourceFirstFrame != ClipRanges[i].firstFrame ||
                    entry.sourceLastFrame != ClipRanges[i].lastFrame)
                {
                    return false;
                }
            }

            return true;
        }

        private static AnimationClip LoadCombinedTake()
        {
            UnityEngine.Object[] assets = AssetDatabase.LoadAllAssetsAtPath(ModelPath);
            AnimationClip namedTake = null;
            AnimationClip previewTake = null;
            AnimationClip longestClip = null;
            var candidates = new List<string>();
            for (int i = 0; i < assets.Length; i++)
            {
                AnimationClip clip = assets[i] as AnimationClip;
                if (clip == null) continue;
                candidates.Add(clip.name + "=" + clip.length.ToString("0.###") + "s@" + clip.frameRate.ToString("0.###") + "fps/curves=" + AnimationUtility.GetCurveBindings(clip).Length);
                bool isPreviewClip = clip.name.StartsWith("__preview__", StringComparison.OrdinalIgnoreCase);
                if (isPreviewClip)
                {
                    if (previewTake == null || clip.length > previewTake.length) previewTake = clip;
                    continue;
                }

                if (longestClip == null || clip.length > longestClip.length) longestClip = clip;
                if (string.Equals(clip.name, CombinedTakeName, StringComparison.Ordinal) &&
                    (namedTake == null || clip.length > namedTake.length)) namedTake = clip;
            }

            Debug.Log("[Rat Habitat] Hand Painted Rat imported animation candidates: " +
                (candidates.Count == 0 ? "<none>" : string.Join(", ", candidates.ToArray())));

            // A stale importer cache can expose a short Take 001 alongside the
            // full __preview__Take 001. Prefer only a clip that reaches the
            // confirmed final source frame; never bake from a short take.
            float minimumFullTimelineLength = (SourceTimelineLastFrame - 1) / SourceFrameRateFallback;
            if (namedTake != null && namedTake.length >= minimumFullTimelineLength - (1f / SourceFrameRateFallback) * 0.5f) return namedTake;
            if (previewTake != null && previewTake.length >= minimumFullTimelineLength - (1f / SourceFrameRateFallback) * 0.5f) return previewTake;
            return longestClip;
        }

        private static AnimationClip CreateOrReplaceSlicedClip(AnimationClip source, ClipRange range)
        {
            string assetPath = ClipFolderPath + "/" + range.name + ".anim";
            AnimationClip existing = AssetDatabase.LoadAssetAtPath<AnimationClip>(assetPath);
            if (existing != null) AssetDatabase.DeleteAsset(assetPath);

            AnimationClip clip = new AnimationClip
            {
                name = range.name,
                frameRate = source.frameRate > 0f ? source.frameRate : SourceFrameRateFallback,
                legacy = false,
                wrapMode = range.loop ? WrapMode.Loop : WrapMode.Once,
            };

            float frameRate = clip.frameRate;
            float startTime = Mathf.Max(0f, (range.firstFrame - 1) / frameRate);
            float endTime = GetEndTime(range, frameRate);
            // The imported preview take reports its final source frame as the
            // clip length (frame 256 at 10.625s for 24fps). GetEndTime keeps
            // the historical exclusive boundary for normal ranges while the
            // walk range uses its explicit inclusive final source frame so
            // the following stiff transition cannot be sampled.

            EditorCurveBinding[] curveBindings = AnimationUtility.GetCurveBindings(source);
            for (int i = 0; i < curveBindings.Length; i++)
            {
                AnimationCurve sourceCurve = AnimationUtility.GetEditorCurve(source, curveBindings[i]);
                AnimationCurve slicedCurve = SliceCurve(sourceCurve, startTime, endTime);
                if (slicedCurve != null && slicedCurve.length > 0)
                {
                    AnimationUtility.SetEditorCurve(clip, curveBindings[i], slicedCurve);
                }
            }

            EditorCurveBinding[] objectBindings = AnimationUtility.GetObjectReferenceCurveBindings(source);
            for (int i = 0; i < objectBindings.Length; i++)
            {
                ObjectReferenceKeyframe[] sourceKeys = AnimationUtility.GetObjectReferenceCurve(source, objectBindings[i]);
                ObjectReferenceKeyframe[] slicedKeys = SliceObjectReferenceCurve(sourceKeys, startTime, endTime);
                if (slicedKeys != null && slicedKeys.Length > 0)
                {
                    AnimationUtility.SetObjectReferenceCurve(clip, objectBindings[i], slicedKeys);
                }
            }

            AnimationEvent[] sourceEvents = AnimationUtility.GetAnimationEvents(source);
            var slicedEvents = new List<AnimationEvent>();
            for (int i = 0; i < sourceEvents.Length; i++)
            {
                if (sourceEvents[i].time < startTime || sourceEvents[i].time > endTime) continue;
                AnimationEvent copy = sourceEvents[i];
                copy.time -= startTime;
                slicedEvents.Add(copy);
            }
            AnimationUtility.SetAnimationEvents(clip, slicedEvents.ToArray());

            // Animator states use AnimationClipSettings.loopTime for Mecanim
            // looping. AnimationClip.wrapMode alone is not sufficient here.
            AnimationClipSettings settings = AnimationUtility.GetAnimationClipSettings(clip);
            settings.startTime = 0f;
            settings.stopTime = Mathf.Max(1f / frameRate, endTime - startTime);
            settings.loopTime = range.loop;
            settings.loopBlend = false;
            settings.keepOriginalPositionY = true;
            settings.keepOriginalPositionXZ = true;
            settings.keepOriginalOrientation = true;
            AnimationUtility.SetAnimationClipSettings(clip, settings);

            AssetDatabase.CreateAsset(clip, assetPath);
            return clip;
        }

        private static AnimationCurve SliceCurve(AnimationCurve source, float startTime, float endTime)
        {
            if (source == null || source.length == 0) return null;

            var keys = new List<Keyframe>();
            AddBoundaryKey(keys, source, startTime, startTime);
            for (int i = 0; i < source.length; i++)
            {
                Keyframe key = source[i];
                if (key.time <= startTime || key.time >= endTime) continue;
                key.time -= startTime;
                keys.Add(key);
            }
            AddBoundaryKey(keys, source, endTime, startTime);
            return keys.Count == 0 ? null : new AnimationCurve(keys.ToArray());
        }

        private static void AddBoundaryKey(List<Keyframe> keys, AnimationCurve source, float sourceTime, float localOffset)
        {
            float localTime = sourceTime - localOffset;
            if (keys.Count > 0 && Mathf.Abs(keys[keys.Count - 1].time - localTime) < 0.0001f) return;

            Keyframe boundary = new Keyframe(localTime, source.Evaluate(sourceTime));
            keys.Add(boundary);
        }

        private static ObjectReferenceKeyframe[] SliceObjectReferenceCurve(ObjectReferenceKeyframe[] source, float startTime, float endTime)
        {
            if (source == null || source.Length == 0) return null;
            var keys = new List<ObjectReferenceKeyframe>();
            for (int i = 0; i < source.Length; i++)
            {
                if (source[i].time < startTime || source[i].time > endTime) continue;
                ObjectReferenceKeyframe key = source[i];
                key.time -= startTime;
                keys.Add(key);
            }
            return keys.ToArray();
        }

        private static int CountAnimatedBindings(AnimationClip clip)
        {
            int count = 0;
            EditorCurveBinding[] bindings = AnimationUtility.GetCurveBindings(clip);
            for (int i = 0; i < bindings.Length; i++)
            {
                AnimationCurve curve = AnimationUtility.GetEditorCurve(clip, bindings[i]);
                if (curve == null || curve.length < 2) continue;
                float first = curve[0].value;
                for (int k = 1; k < curve.length; k++)
                {
                    if (Mathf.Abs(curve[k].value - first) > 0.0001f)
                    {
                        count++;
                        break;
                    }
                }
            }
            return count;
        }

        private static int CountAnimatedBodyBindings(AnimationClip clip)
        {
            int count = 0;
            EditorCurveBinding[] bindings = AnimationUtility.GetCurveBindings(clip);
            for (int i = 0; i < bindings.Length; i++)
            {
                if (!IsBodyMotionBinding(bindings[i])) continue;
                AnimationCurve curve = AnimationUtility.GetEditorCurve(clip, bindings[i]);
                if (curve == null || curve.length < 2) continue;
                float first = curve[0].value;
                for (int k = 1; k < curve.length; k++)
                {
                    if (Mathf.Abs(curve[k].value - first) > 0.0001f)
                    {
                        count++;
                        break;
                    }
                }
            }
            return count;
        }

        private static bool IsBodyMotionBinding(EditorCurveBinding binding)
        {
            string path = (binding.path ?? string.Empty).ToLowerInvariant();
            string[] bodyFragments =
            {
                "leg", "foot", "paw", "head", "ear", "chest", "spine", "tail", "body", "neck", "arm"
            };
            for (int i = 0; i < bodyFragments.Length; i++)
            {
                if (path.Contains(bodyFragments[i])) return true;
            }
            return false;
        }

        private static void RebuildController(AnimationClip[] slicedClips)
        {
            AnimatorController controller = AssetDatabase.LoadAssetAtPath<AnimatorController>(ControllerPath);
            if (controller == null)
            {
                Debug.LogError("[Rat Habitat] Could not find the Hand Painted Rat Animator Controller at " + ControllerPath);
                return;
            }

            AnimatorControllerLayer[] layers = controller.layers;
            if (layers == null || layers.Length == 0 || layers[0].stateMachine == null)
            {
                Debug.LogError("[Rat Habitat] Hand Painted Rat controller has no usable Base Layer state machine.");
                return;
            }

            AnimatorStateMachine stateMachine = layers[0].stateMachine;
            ChildAnimatorState[] childStates = stateMachine.states;
            for (int i = 0; i < childStates.Length; i++)
            {
                if (childStates[i].state != null) stateMachine.RemoveState(childStates[i].state);
            }

            AnimatorState firstState = null;
            for (int i = 0; i < slicedClips.Length; i++)
            {
                if (slicedClips[i] == null) continue;
                AnimatorState state = stateMachine.AddState(slicedClips[i].name);
                state.motion = slicedClips[i];
                state.speed = 1f;
                state.writeDefaultValues = true;
                if (firstState == null) firstState = state;
            }
            stateMachine.defaultState = firstState;

            EditorUtility.SetDirty(controller);
            AssetDatabase.SaveAssets();
            Selection.activeObject = controller;
            Debug.Log("[Rat Habitat] Baked and assigned Hand Painted Rat clips from exact source ranges: " + DescribeRanges());
        }

        private static string DescribeRanges()
        {
            var descriptions = new List<string>();
            for (int i = 0; i < ClipRanges.Length; i++)
            {
                descriptions.Add(ClipRanges[i].name + "=" + ClipRanges[i].firstFrame + "-" + ClipRanges[i].lastFrame);
            }
            return string.Join(", ", descriptions.ToArray());
        }

        private static void EnsureFolder(string folderPath)
        {
            if (AssetDatabase.IsValidFolder(folderPath)) return;
            string[] parts = folderPath.Split('/');
            string current = parts[0];
            for (int i = 1; i < parts.Length; i++)
            {
                string next = current + "/" + parts[i];
                if (!AssetDatabase.IsValidFolder(next)) AssetDatabase.CreateFolder(current, parts[i]);
                current = next;
            }
        }
    }

    internal sealed class HandPaintedRatAnimationPostprocessor : AssetPostprocessor
    {
        private static void OnPostprocessAllAssets(
            string[] importedAssets,
            string[] deletedAssets,
            string[] movedAssets,
            string[] movedFromAssetPaths)
        {
            for (int i = 0; i < importedAssets.Length; i++)
            {
                if (!string.Equals(importedAssets[i], "Assets/Art/HandPaintedRat/HandPaintedRat.fbx", StringComparison.OrdinalIgnoreCase)) continue;
                HandPaintedRatAnimationSetup.ScheduleBakeAndRebuild();
                return;
            }
        }
    }
}
#endif
